name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug file structure
      run: ls -la  # Llista els fitxers per depurar

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+\.\d+" | cut -d. -f1)
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        chromedriver --version

    - name: Verify Chrome and ChromeDriver
      run: |
        google-chrome --version || (echo "Chrome no està instal·lat correctament" && exit 1)
        chromedriver --version || (echo "ChromeDriver no està instal·lat correctament" && exit 1)

    - name: Start Flask app
      run: |
        python app.py > flask.log 2>&1 &
        for i in {1..10}; do
          curl -s http://127.0.0.1:5000 && break || sleep 3
        done
        curl -f http://127.0.0.1:5000 || (echo "Flask no està en execució" && cat flask.log && exit 1)

    - name: Run Selenium tests
      run: |
        python -m unittest discover -v || (echo "Els tests han fallat"; exit 1)
